### ISSUE TITLE
show user ID in responsibilities tab

### ISSUE THREAD

**Issue by trowik** [adfinis/timed#111]
Show supervisee IDs next to name in responsibilities tab in user profile

**Comment by c0rydoras** [comment]
what would be the usecase of this?

**Comment by trowik** [comment]
boah I don't know, why I copied that issue
I think it might have had something to do with some other tools we use

**Comment by c0rydoras** [comment]
is this still a thing or can we close this?

**Comment by trowik** [comment]
let's close it for now
