### ISSUE TITLE
open refactorings for ember 4

### ISSUE THREAD

**Issue by derrabauke** [adfinis/timed#118]
# Overview
This should summarize open tasks after the adfinis/timed-frontend#710 ember octane upgrade.
Run `pnpm lint:hbs` and `pnpm lint:js` to get an overview which classes are still using deprecated code.

## Work to do
Those parts of the app need a major refactoring before we can upgrade to ember 4:
- [x] refactor yield only templates
- [ ] refactor classic ember components
- [x] refactor all `LinkTo` component invocations which make use of the `tagName` prop
- [x] refactor all occurrences `Mixins`

Further the `ember-deprecation-workflow` plugin is still active. In a next steep we need to set all `silenced` errors to `throw` and work trough the issues. This can be done in a step by step ordered process and should resolve all the listed issues from above.

**Comment by c0rydoras** [comment]
@derrabauke whats the current state of this?
