### ISSUE TITLE
Add option to "hide" archived tasks in the "project" management

### ISSUE THREAD

**Issue by mjoxy** [adfinis/timed#129]
When you have to add and archive a lot of tasks within a project, you will lose the overview very fast because there is no option to hide the already archived tasks. A checkbox to enable "show archived" could solve that issue.

**Comment by c0rydoras** [comment]
is this the same as #67?

**Comment by mjoxy** [comment]
thanks for taking a look @c0rydoras. No not exactly. 
What I think is in the tab "Projects", when you chose a project and you get the list of all tasks. At the moment there is no option to hide archived tasks there, and there are projects that are dynamic, so you can have dozens or hundreds of archived tasks. This kills the overview.

**Comment by c0rydoras** [comment]
Something like this?

**Comment by mjoxy** [comment]
@c0rydoras yes exactly this
