### ISSUE TITLE
Detect authentication issues

### ISSUE THREAD

**Issue by winged** [adfinis/timed#132]
Sometimes, the authentication runs out of sync. In those cases, the frontend thinks it's still logged in, despite API calls returning a HTTP/401.

The data that's missing from the API call then causes the app to hang with a white page that requires users to clear local storage etc.
This could be fixed, such that in those cases (API returning HTTP/401 or similar), the login procedure should be triggered.

**Comment by c0rydoras** [comment]
@derrabauke any updates on this?

**Comment by derrabauke** [comment]
Lately no occurrences of this issue. Let's close for now.
