### ISSUE TITLE
Project Overview: Task management

### ISSUE THREAD

**Issue by sinicis** [adfinis/timed#134]
**Bug description**

If you want to add a task underneath customer "XYZ" within project "SLA Operations". But you realize you're in the wrong project (p.e. "SLA Wartung") after you've already pressed the "Add Task" button. So you switch the project, fill out the form and save the new task. The new task is now created within project "SLA Wartung" instead of "SLA Operations".

**How to reproduce**

1.) Choose "Projects" in top menu
2.) Select customer "XYZ" and p.e. project "SLA Wartung"
3.) Click "Add Task" (new form appears underneath the task list)
4.) Change project to "SLA Operations" (side reloads)
5.) Fill out "Add task" form and save it

**Further notes**

It acts the same way when editing a task. 

Per example you are at "CONCORDIA" -> "SLA Wartung" and you want to edit "Administration". So you click on it and the form appears. Then change project t0 "SLA Operations". Change p.e. the name of the task and save it. The changes will be applied within project "SLA Wartung"

**Resolution**

I see two options to fix it:
1. Form has to be refreshed so the action takes place in the right project.
1. Always disable/hide the form when changing projects

Option 1 has a disadvantage if you want to edit a task which does not exist in the project you're switching to.

**Comment by c0rydoras** [comment]
this is a very old issue and i am unable to replicate this. i'll close it for now, if this is still an issue re-open it. :)
