### ISSUE TITLE
Copy link to task for recording

### ISSUE THREAD

**Issue by winged** [adfinis/timed#136]
When working together in a team, we often ask "where can I record the time for this"? Which is replied to with a more-or-less accurate description of the customer/project/task triplet.

How about we could copy a link to the task? I would expect the following use cases to work (No UI/UX expert, so behaviour suggestion may vary)

Opening the link to a task would activate a dialog with the following options:
* Start recording activity
* Create timesheet entry

The task links should be rendered everywhere where a task name is shown - activity list, timesheet, and potentially even in the project admin and even the analysis page. This could also replace the "play" button in the activity list, so you can go back to activities and instead of restarting it, also have the option to refer the link to someone else, or start tracking/create an entry.

**Comment by hairmare** [comment]
it might be time to follow up on this 🥺

**Comment by c0rydoras** [comment]
superseded by #79
