### ISSUE TITLE
[BUG]:  tour steps attendances highlights wrong part of the app

### ISSUE THREAD

**Issue by derrabauke** [adfinis/timed#198]
### Description

Onboarding tour at attendance step highlights wrong part of the app (see screenshot).

### Steps to Reproduce

Start timed demo tour, click *next* until you've reached the attendance chapter.

### Expected Behavior

Highlight the attendance area, not the time table.

### Attachments

![image](https://github.com/adfinis/timed/assets/10029904/a8c454e6-1d56-4ab2-9b05-cbc1bcaf2b06)

### Version

4.0.0

### Required

- [X] I have checked past issues to see if this bug has already been reported.

**Comment by MitanOmar** [comment]
@derrabauke since the on-boarding is something belong to the new users, what if there is no attendances to highlights ?

**Comment by derrabauke** [comment]
> @derrabauke since the on-boarding is something belong to the new users, what if there is no attendances to highlights ?

There area to highlight is still there even if no entries are in it yet, right?

**Comment by hairmare** [comment]
shouldn't the tour have made you create an attendance so you can follow along with the description from the tour box?

**Comment by MitanOmar** [comment]
@hairmare since now, it's just show the area, and the UX taking care of the others
