### ISSUE TITLE
[BUG]: You do not have permission to perform this action when stopping an activity

### ISSUE THREAD

**Issue by hairmare** [adfinis/timed#233]
### Description

I'm unable to stop an activity that i started earlier today.

### Steps to Reproduce

1. be me
2. start activity
3. be done with working
4. click stop button next to running activity
5. receive error

### Expected Behavior

It stops the activity

### Attachments

I see the following error in the response to a PATCH req to https://timed.adfinis.com/api/v1/activities/214087
```json
{
  "errors": [
    {
      "detail": "You do not have permission to perform this action.",
      "status": "403",
      "source": {
        "pointer": "/data"
      },
      "code": "permission_denied"
    }
  ]
}
```

### Additional Context

I generated HAR if need be.

It's not logging much on the backend:

```
Forbidden: /api/v1/activities/214087
403 PATCH /api/v1/activities/214087 (10.100.18.71) 204.12ms
```

### Version

4.1.9

### Required

- [X] I have checked past issues to see if this bug has already been reported.

**Comment by hairmare** [comment]
This activity was started before the update to 4.1.9 and i wanted to stop it after the update. Not sure if relevant, but if that was the only issue then we can safely close this issue if it's not something that happens with every update.

**Comment by c0rydoras** [comment]
This happens nearly every deployment and is starting to annoy me
