### ISSUE TITLE
Remove django-multiselectfield dependency

### ISSUE THREAD

**Issue by hairmare** [adfinis/timed#25]
The `django-multiselect` library is a tad unmaintained and it looks like we can remove it completely given we only really use it for the weekdays feature right now.

We used this workaround:

> [goinnn/django-multiselectfield#131 (comment)](https://github.com/goinnn/django-multiselectfield/issues/131#issuecomment-1368239342)

Look [here](https://github.com/goinnn/django-multiselectfield/issues) for more info... the library hasn't been maintained for years at this point.

_Originally posted by @hairmare in https://github.com/adfinis/timed-backend/issues/1028#issuecomment-2057185772_

**Comment by c0rydoras** [comment]
I see two ways to do this:
- we make it a simple text input and the UX gets worse
- we copy the code over to timed (its not much) and remove things we don't need

**Comment by c0rydoras** [comment]
@hairmare @adfinis/dev-backend What would you recommend?

**Comment by hairmare** [comment]
If the UX in question is deep in Django admin land, then we might want to mock up some screenshots and ask the affected end-users for their input.

Copying the code might be just as viable. My gut feeling is that some refactoring would make it pretty much it's own thing anyway if we remove all the bits we don't use.

IMHO if we really want to improve the UX, then we should start thinking if we can completely replace Django admin in full. I'm not sure there is much reason as to why the contents currently managed in Django admin couldn't be exposed in the Ember frontend as their own feature. If we roadmap that, it would help push the removal case.

My gut feeling is that the weekday feature we found is used so rarely that degrading the UX with a simple text field is totally ok. AFAIK the records have almost no churn and there are really few of them.
