### ISSUE TITLE
[REFACTOR]: get rid of adcssy.scss

### ISSUE THREAD

**Issue by c0rydoras** [adfinis/timed#256]
### What to refactor

stuff in adcssy.scss

### Why refactor it

its not maintainable

### How to refactor it

1. find replacement e.g. uikit which we use in our other projects
2. rewrite easy parts to uikit
3. ensure there are no visual regressions
4. merge, be happy, more maintainable

### Required

- [X] I have checked past issues to ensure that this isn't a duplicate.

**Comment by MitanOmar** [comment]
@c0rydoras what are you trying to fix ?

**Comment by c0rydoras** [comment]
Timed

**Comment by derrabauke** [comment]
Very good point! Let's do that. You could use https://github.com/garris/ember-backstop or https://github.com/percy/percy-ember to test for visual regression. It runs locally as well, I you don't want to set it up permanently.
