### ISSUE TITLE
session service is not return user info with ember data model

### ISSUE THREAD

**Issue by MitanOmar** [adfinis/timed#26]
**Describe the bug**
Timed use `ember-simple-auth-oidc`, which it's built in top of `ember-simple-auth`,
when first time login, the `session` service including the data of the current user info and it's an instance of [data model](https://github.com/adfinis/timed-frontend/blob/main/app/models/user.js)

but when the token is expire, `ember-simple-auth-oidc` refresh the token, but the user information is a pure object that come from `keycloak`, without encapsulating it inside ember data model  and we can not access the helper that defined in [user data model](https://github.com/adfinis/timed-frontend/blob/main/app/models/user.js)

**To Reproduce**
open multi timed tab, and go to `https://timed.adfinis.com/reports` and in another page go to `https://timed.adfinis.com/analysis` page, and wait a few minutes until you are sure the token is expire

**Screenshots**
in the console, you got a lot of this error, and each time you select a report or try to change the date of timesheet, you get another error.
and the source of this error coming from  [Report Abilities](https://github.com/adfinis/timed-frontend/blob/main/app/abilities/report.js) file

![Screenshot](https://github.com/adfinis/timed-frontend/assets/22119228/75b82188-c81e-4047-b537-1c210aedb34a)

and there is an open merge request to give a temporary solution to ignore this issue adfinis/timed-frontend#1199

**Comment by derrabauke** [comment]
https://github.com/adfinis/timed-frontend/pull/1201 this needs to be migrated to this new repo!

**Comment by MitanOmar** [comment]
i am checking the PR, and i will include it

**Comment by c0rydoras** [comment]
@derrabauke it has been ported and merged: #150

**Comment by c0rydoras** [comment]
Tested and confirmed to be fixed in https://github.com/adfinis/timed/tree/v4.0.3
