### ISSUE TITLE
full text search for comments in analysis

### ISSUE THREAD

**Issue by derrabauke** [adfinis/timed#29]
**Is your feature request related to a problem? Please describe.**
When filtering for a certain task, I want to be able to filter the results by certain comments made for the task. This is relevant for task which host a variable amount of smaller subtasks e.g. *Software Maintenance*

**Describe the solution you'd like**
In the *Analysis* and *Statistics* filter I want to be able to search for comments containing specific words. Ideally this would support multiple strings separated by commans and/or regular expressions.

**Additional context**
Maybe add the filter input here after the `task` select.
![image](https://github.com/adfinis/timed-frontend/assets/10029904/39d8e910-6b4e-4ab5-8fc8-9b9ddd86f2fa)

**Comment by hairmare** [comment]
does it have to be regex or is it also time to look into natsearch algos again?

my feeling is that our current psql stack might enable some things that could make some nat-searching possible without much effort

this could be worth more than enabling regex (which i as a techie would still also like)

**Comment by c0rydoras** [comment]
Another question is, do we implement it in the backend or the frontend?

## backend filter
- would be better, as there should be only as much logic in the frontend as required
- not sure how to implement
- new ReDoS vector

## frontend
- slow
- ...

**Comment by derrabauke** [comment]
*Oh fo sho* in the backend. Not sure if we already use the full text search feature. Further there is [regex](https://docs.djangoproject.com/en/dev/ref/models/querysets/#regex) for querysets, but not sure about the value/ReDos ratio. :man_shrugging:
