### ISSUE TITLE
auto-format time when entering

### ISSUE THREAD

**Issue by smirnov-mi** [adfinis/timed#30]
**Is your feature request related to a problem? Please describe.**
 Hi guys, can I log a feature request for timed ?     Would it be possible to get "auto-formatting" during entering the time , e.g. if I type in "730" - it would be auto-formatted into "07:30",    or "1615" -> "16:15",    "15" would become "15:00".  ?  

**Describe the solution you'd like**
as above, e.g.
07 becomes 07:00
15 becomes 15:00
830 becomes 08:30
1615 becomes 16:15

**Describe alternatives you've considered**
well, alternative solution is how it works now.

**Comment by hairmare** [comment]
me likey! thanks @smirnov-mi !
