### ISSUE TITLE
[BUG]: Magic Link is not working correctly

### ISSUE THREAD

**Issue by MitanOmar** [adfinis/timed#343]
### Description

The magic link only include the task id in the URL, it's not including the customer id and the project id
![Screenshot from 2024-07-15 11-33-29](https://github.com/user-attachments/assets/771247a8-0d8f-43ca-a722-09d7b51e6366)

### Steps to Reproduce

* Click Magic Link Button.
* select a customer and project and task

### Expected Behavior

The Link should include the customer id and the project id in the link

### Version

4.1.10

### Required

- [X] I have checked past issues to see if this bug has already been reported.

**Comment by c0rydoras** [comment]
I don't see the issue here, task has a foreign key to project and that project has a foreign key to customer, this would be redundant information afaict

**Comment by c0rydoras** [comment]
those can be inferred from the task?

**Comment by MitanOmar** [comment]
Check this
![image](https://github.com/user-attachments/assets/0ad175e7-8cae-4cbd-adae-d9ca0777d2a4)

**Comment by c0rydoras** [comment]
That is in fact a bug

**Comment by c0rydoras** [comment]
But shouldn't be caused by customer and project not being inlcuded in the URL

**Comment by MitanOmar** [comment]
anyway i will take care of fixing it, whatever is the solution of it

**Comment by c0rydoras** [comment]
Nice :)
