### ISSUE TITLE
[ENHANCEMENT]: Allow PM to revert verified positions as long as they are not billed

### ISSUE THREAD

**Issue by tk0e** [adfinis/timed#382]
### Your proposed enhancement

Once verified, a PM can not revert Timed positions to an un-verified status. The reason for this restriction was, that verified entries could have already been invoiced to customers and reverting them could potentially lead into errors with our billing.

A while ago a new flag "billed" was introduced, that specifically marks entries, once they were invoiced to a customer. This would allow to remove the restrictions for PM to revert verified entries in the projects they are responsible for.

The restriction should be imposed on Timed positions marked as billed, though. 

Since there are projects that are pre-paid and therefore marked as "billed" by default (or once they are verified, I am not sure), reverting positions in this kind of projects (i.e. SLA Operations) would still not be possible. 

### Enhancement Impact

Hopefully, this enhancement would give a PM more flexibility in when to verifiy its report and help to get this done quickly and regularly. Since one excuse, that verifications are only done after weeks, is often, that there is no going back, once entries are verified.

### Additional context

I would be interested in your opinion about this, @nis65?

### Required

- [X] I have checked past issues to ensure that this isn't a duplicate.

**Comment by tk0e** [comment]
Duplicate. I knew I already discussed this with someone and asked him to open an issue. But I was unable to find it.

**Comment by nis65** [comment]
Thanks @paraenggu and @tk0e for bringing this up again / finding the old request. :-)
