### ISSUE TITLE
[BUG]: Attendence until midnight can't be saved

### ISSUE THREAD

**Issue by tongpu** [adfinis/timed#462]
### Description

When adding an attendance until midnight I receive an error message that the attendance can't be saved.

### Steps to Reproduce

1. Go to the attendances tab
2. Add an attendance from any time until 00:00
3. Receive an error message from the backend
```json
{
  "errors": [
    {
      "detail": "An attendance may not end before it starts.",
      "status": "400",
      "source": {
        "pointer": "/data"
      },
      "code": "invalid"
    }
  ]
}
```

### Expected Behavior

1. Go to the attendances tab
2. Add an attendance from any time until 00:00
3. Attendance is saved, because 00:00 on the right border of the screen is recognized as 00:00 of the next day.

### Version

v4.4.1

### Required

- [X] I have checked past issues to see if this bug has already been reported.

**Comment by c0rydoras** [comment]
#440  🙃

**Comment by tongpu** [comment]
It was late, so I probably didn't check closed issues. :cookie:
