### ISSUE TITLE
[BUG]: Analysis - Task flags are hidden on select

### ISSUE THREAD

**Issue by karras** [adfinis/timed#540]
### Description

If a task has set one of the available flags (e.g. `Rejected` or `Review`) and one selects it in the context of Analysis, the current CSS hides the check boxes.

### Steps to Reproduce

1. Report a task with the `Review` flag
2. Navigate to Analysis
3. Adjust the filters to see the task
4. Click on it to select it
5. The defined flags are "hidden" as they have the same colors than the selected column background

### Expected Behavior

The check boxes switch to another icon/font color remain visible, once the column/task was selected.

### Attachments

![image](https://github.com/user-attachments/assets/344808db-53d5-404b-b735-bd7804c88980)

### Version

v5.0.1

### Required

- [X] I have checked past issues to see if this bug has already been reported.

**Comment by c0rydoras** [comment]
This is also an issue in other places (e.g. activities), thanks for catching this!
