### ISSUE TITLE
 Archivierte Projekte in der User-Übersicht

### ISSUE THREAD

**Issue by trowik** [adfinis/timed#67]
## Current behavior
In the personal user view (top right) in the "Responsabilities" tab, each user gets an overview of the projects (bottom left) to which the user is assigned as a reviewer. Archived projects are also currently displayed there.

![image](https://github.com/user-attachments/assets/94cc9bd3-dc17-4b05-ad93-065375ac03f8)

## Expected behavior
Archived projects aren't displayed.

**Comment by c0rydoras** [comment]
@trowik is this still a thing?

**Comment by trowik** [comment]
@c0rydoras yes

**Comment by c0rydoras** [comment]
could you maybe make the description more detailed? respectively maybe it would make sense to make this a discussion

**Comment by trowik** [comment]
I don't think there is really much more to add.

The feature would affect the following lines:
https://github.com/adfinis/timed/blob/be835c27cfb1acb5e296c24d9260917e608da771/frontend/app/users/edit/responsibilities/controller.js#L17-L24

**Comment by c0rydoras** [comment]
we could make it a toggle for instance

**Comment by trowik** [comment]
> we could make it a toggle for instance

We could potentially extend the "toggle archived"-feature to other parts of the application, like filters for example
